var data_cambodia = 
{
	templates: [
				{
					name: "GMS Data Template",
					file:"GMS_Data_Template.xlsx",
					sheets: [
								{
									sheet_type: "MULTIPLE_DE_OU_PE",
									sheet_no: 1,
									orgUnitIdScheme: "UID",
									dataElementIdScheme: "CODE",
									idScheme: "CODE",
									oucode_col: "A",
									month_col: "F", 
									year_col: "E",
									data_starting_row : 3,
									last_data_column : "BZ",
									key_coulmn: "A",
									
									agg_des: 
										[			
											{ deuid: "BR01", cocuid: "default", col_no: "G"},
											{ deuid: "BR02", cocuid: "default", col_no: "H"}
/*											
											{ deuid: "BR03", cocuid: "default", col_no: "I"},
											{ deuid: "BR04", cocuid: "default", col_no: "J"},
											{ deuid: "BR05", cocuid: "default", col_no: "K"},
											{ deuid: "BR06", cocuid: "default", col_no: "L"},
											{ deuid: "BR07", cocuid: "default", col_no: "M"},
											{ deuid: "BR08", cocuid: "default", col_no: "N"},
											{ deuid: "BR09", cocuid: "default", col_no: "O"},
											{ deuid: "BR10", cocuid: "default", col_no: "P"},
											{ deuid: "BR11", cocuid: "default", col_no: "Q"},
											{ deuid: "BR12", cocuid: "default", col_no: "R"},
											{ deuid: "BR13", cocuid: "default", col_no: "S"},
											{ deuid: "BR14", cocuid: "default", col_no: "T"},
											{ deuid: "BR15", cocuid: "default", col_no: "U"},
											{ deuid: "BR16", cocuid: "default", col_no: "V"},
											{ deuid: "BR17", cocuid: "default", col_no: "W"},
											{ deuid: "BR18", cocuid: "default", col_no: "X"},
											{ deuid: "BR19", cocuid: "default", col_no: "Y"},
											{ deuid: "BR20", cocuid: "default", col_no: "Z"},
											{ deuid: "BR21", cocuid: "default", col_no: "AA"},
											{ deuid: "BR22", cocuid: "default", col_no: "AB"},
											{ deuid: "BR23", cocuid: "default", col_no: "AC"},
											{ deuid: "BR24", cocuid: "default", col_no: "AD"},
											{ deuid: "BR25", cocuid: "default", col_no: "AE"},
											{ deuid: "BR26", cocuid: "default", col_no: "AF"},
											{ deuid: "BR27", cocuid: "default", col_no: "AG"},
											{ deuid: "BR28", cocuid: "default", col_no: "AH"},
											{ deuid: "BR29", cocuid: "default", col_no: "AI"},
											{ deuid: "BR30", cocuid: "default", col_no: "AJ"},
											{ deuid: "BR31", cocuid: "default", col_no: "AK"},
											{ deuid: "BR32", cocuid: "default", col_no: "AL"},
											{ deuid: "BR33", cocuid: "default", col_no: "AM"},
											{ deuid: "BR34", cocuid: "default", col_no: "AN"},
											{ deuid: "BR35", cocuid: "default", col_no: "AO"},
											{ deuid: "BR36", cocuid: "default", col_no: "AP"},
											{ deuid: "BR37", cocuid: "default", col_no: "AQ"},
											{ deuid: "BR38", cocuid: "default", col_no: "AR"},
											{ deuid: "BR39", cocuid: "default", col_no: "AS"},
											{ deuid: "BR40", cocuid: "default", col_no: "AT"},
											{ deuid: "BR41", cocuid: "default", col_no: "AU"},
											{ deuid: "EL01", cocuid: "default", col_no: "AV"},
											{ deuid: "EL02", cocuid: "default", col_no: "AW"},
											{ deuid: "EL03", cocuid: "default", col_no: "AX"},
											{ deuid: "EL04", cocuid: "default", col_no: "AY"},
											{ deuid: "EL05", cocuid: "default", col_no: "AZ"},
											{ deuid: "EL06", cocuid: "default", col_no: "BA"},
											{ deuid: "EL07", cocuid: "default", col_no: "BB"},
											{ deuid: "EL08", cocuid: "default", col_no: "BC"},
											{ deuid: "EL09", cocuid: "default", col_no: "BD"},
											{ deuid: "EL10", cocuid: "default", col_no: "BE"},
											{ deuid: "EL11", cocuid: "default", col_no: "BF"},
											{ deuid: "EL12", cocuid: "default", col_no: "BG"},
											{ deuid: "EL13", cocuid: "default", col_no: "BH"},
											{ deuid: "EL14", cocuid: "default", col_no: "BI"},
											{ deuid: "EL15", cocuid: "default", col_no: "BJ"},
											{ deuid: "EL16", cocuid: "default", col_no: "BK"},
											{ deuid: "EL17", cocuid: "default", col_no: "BL"},
											{ deuid: "EL18", cocuid: "default", col_no: "BM"},
											{ deuid: "EL19", cocuid: "default", col_no: "BN"},
											{ deuid: "EL20", cocuid: "default", col_no: "BO"},
											{ deuid: "EL21", cocuid: "default", col_no: "BP"},
											{ deuid: "EL22", cocuid: "default", col_no: "BQ"},
											{ deuid: "EL23", cocuid: "default", col_no: "BR"},
											{ deuid: "EL24", cocuid: "default", col_no: "BS"},
											{ deuid: "EL25", cocuid: "default", col_no: "BT"},
											{ deuid: "EL26", cocuid: "default", col_no: "BU"},
											{ deuid: "EL27", cocuid: "default", col_no: "BV"},
											{ deuid: "MM01", cocuid: "default", col_no: "BW"},
											{ deuid: "MM02", cocuid: "default", col_no: "BX"},
											{ deuid: "MM03", cocuid: "default", col_no: "BY"},
											{ deuid: "MM04", cocuid: "default", col_no: "BZ"}									
*/											
										]
								}
							]
				}
			]
}